// @ts-check
import withNuxt from "./.nuxt/eslint.config.mjs";

const INLINE_ELEMENTS = [
  "AnchorLink",
  "pre",
  "textarea",
  "router-link",
  "RouterLink",
  "nuxt-link",
  "NuxtLink",
  "u-link",
  "ULink",
  "a",
  "abbr",
  "audio",
  "b",
  "bdi",
  "bdo",
  "canvas",
  "cite",
  "code",
  "data",
  "del",
  "dfn",
  "em",
  "i",
  "iframe",
  "ins",
  "kbd",
  "label",
  "map",
  "mark",
  "noscript",
  "object",
  "output",
  "picture",
  "q",
  "ruby",
  "s",
  "samp",
  "small",
  "span",
  "strong",
  "sub",
  "sup",
  "svg",
  "time",
  "u",
  "var",
  "video",
];

export default withNuxt({
  rules: {
    "curly": "error",
    "vue/multiline-html-element-content-newline": ["error", {
      ignoreWhenEmpty: true,
      ignores: INLINE_ELEMENTS,
      allowEmptyLines: false,
    }],
    "vue/singleline-html-element-content-newline": ["warn", {
      ignoreWhenNoAttributes: true,
      ignoreWhenEmpty: true,
      ignores: INLINE_ELEMENTS,
      externalIgnores: [],
    }],
    "@typescript-eslint/no-non-null-assertion": "error",
  },
});
